trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Configuring Git for synchronization..."

    # Set up Git user information
    git config --global user.name "$(user_name)"
    git config --global user.email "$(user_email)"

    # Clone the Azure DevOps repository (Authenticate using PAT)
    git clone https://$(AZURE_PAT)@dev.azure.com/TeamTemp/EmojiDetector/_git/EmojiDetector
    cd EmojiDetector

    # Add GitHub as a remote repository (Authenticate using PAT)
    git remote add github https://$(GH_PAT)@github.com/Shad0wKilleer/EmojiDetector.git

    # Fetch the latest changes
    git fetch --all

    # Ensure we are on the correct branch
    git checkout -B main origin/main

    # Pull latest changes to prevent conflicts
    git pull --rebase origin main || echo "No new changes from Azure DevOps"
    git pull --rebase github main || echo "No new changes from GitHub"

    # Push changes from Azure DevOps to GitHub
    git push github main --follow-tags

    # Push changes from GitHub to Azure DevOps
    git push origin main --follow-tags
  displayName: 'Synchronize Azure DevOps and GitHub Repositories'
  env:
    AZURE_PAT: $(AZURE_PAT)
    GH_PAT: $(GH_PAT)
