trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Configuring Git for synchronization..."

    # Set up Git user information using predefined variables
    git config --global user.name "$(BUILD_REQUESTEDFOR)"
    git config --global user.email "$(BUILD_REQUESTEDFOREMAIL)"

    # Clone the Azure DevOps repository
    git clone --mirror https://dev.azure.com/YourOrganization/EmojiDetector-SE-Project

    cd EmojiDetector-SE-Project.git

    # Add GitHub as a remote repository
    git remote add github https://github.com/$(BUILD_REQUESTEDFOR)/EmojiDetector.git

    # Fetch the latest changes from both repositories
    git fetch origin
    git fetch github

    # Push changes from Azure DevOps to GitHub
    git push github --all
    git push github --tags

    # Push changes from GitHub to Azure DevOps
    git push origin --all
    git push origin --tags

  displayName: 'Synchronize Azure DevOps and GitHub Repositories'
